### ISSUE TITLE
Wrong function URLs in README

### ISSUE THREAD

**Issue by joaopalmeiro** [feedzai/js-utilities#2]
Hi! 👋 

**Describe the bug**

Some URLs for certain functions have typos or are out of date based on the current function/module names. Here are the ones I found that need to be fixed if I'm correct:

- https://github.com/feedzai/js-utilities/blob/main/src/functions/array/remove-index.ts
- https://github.com/feedzai/js-utilities/blob/main/src/functions/browers/is-browser.ts
- https://github.com/feedzai/js-utilities/tree/main/src/hooks/use-life-ref.ts
- https://github.com/feedzai/js-utilities/blob/main/src/functions/string/title.ts
- https://github.com/feedzai/js-utilities/blob/main/src/functions/array/remove-item.ts
- https://github.com/feedzai/js-utilities/blob/main/src/functions/curry/throttle.ts

Let me know what you think and if I can open a PR, please.

**Comment by JoaoTMDias** [comment]
Thanks @joaopalmeiro, these have been all fixed :)
